import math as m

# Display Settings
RESOLUTION = RES_WIDTH, RES_HEIGHT = 1920, 1080
HALF_RES_WIDTH = RES_WIDTH // 2
HALF_RES_HEIGHT = RES_HEIGHT // 2

# Player Settings
P_X_POS, P_Y_POS = 0,0
P_ANGLE = 0.1
P_VELOCITY = 5
PLAYER_SENSITIVITY = 0.1

# Ray Cast
FOV = m.pi/2.5
RAY_NUM = 960
DELTA_ANGLE = FOV/RAY_NUM

SCREEN_DISTANCE = HALF_RES_WIDTH / m.tan(FOV / 2)
SCALE = RES_WIDTH // RAY_NUM
VIEW_DIST = 200

# Map Settings
BLOCK_SIZE = 100

